/* Generated By:JavaCC: Do not edit this line. ParserImportInputTableTreeConstants.java Version 5.0 */
package gool.recognizer.common.parseImport;

public interface ParserImportInputTableTreeConstants
{
  public int JJTPARSETABLE = 0;
  public int JJTDECL_IMPORT_MAPPING = 1;
  public int JJTGOOL_IMPORT = 2;
  public int JJTPATHSWRAPPER_GOOL = 3;
  public int JJTLIST_PATHS_IMPORT_GOOL = 4;
  public int JJTPATHWRAPPER_GOOL = 5;
  public int JJTINPUT_IMPORTS = 6;
  public int JJTINPUT_IMPORT = 7;


  public String[] jjtNodeName = {
    "parseTable",
    "decl_import_mapping",
    "gool_import",
    "pathsWrapper_gool",
    "list_paths_import_gool",
    "pathWrapper_gool",
    "input_imports",
    "input_import",
  };
}
/* JavaCC - OriginalChecksum=228083e22b4c4145e2e1473a86508d4e (do not edit this line) */
