/* Generated By:JavaCC: Do not edit this line. ParserImportOutputTableTreeConstants.java Version 5.0 */
package gool.generator.common.parseImport;

public interface ParserImportOutputTableTreeConstants
{
  public int JJTPARSETABLE = 0;
  public int JJTDECL_IMPORT_MAPPING = 1;
  public int JJTGOOL_IMPORT = 2;
  public int JJTPATHSWRAPPER_GOOL = 3;
  public int JJTLIST_PATHS_IMPORT_GOOL = 4;
  public int JJTPATHWRAPPER_GOOL = 5;
  public int JJTOUPUT_IMPORTS = 6;
  public int JJTOUPUT_IMPORT = 7;


  public String[] jjtNodeName = {
    "parseTable",
    "decl_import_mapping",
    "gool_import",
    "pathsWrapper_gool",
    "list_paths_import_gool",
    "pathWrapper_gool",
    "ouput_imports",
    "ouput_import",
  };
}
/* JavaCC - OriginalChecksum=c9c430efbf9ab5e748642cb112e832fb (do not edit this line) */
