package gool.ast.constructs;

/**
 * The type of the nodes which allow us to represent the Abstract Syntax Tree of
 * the intermediate language.
 */

public abstract class Node {
	/**
	 * The string representation of this node. It is used to generate the code
	 * for the target language.
	 * 
	 * @return the code generated by this node for the selected language.
	 */

	
	/**
	 * This forces to override the toString;
	 * by forcing to override callGetCode().
	 * See wiki, Nitty Gritty details for more explanations.
	 */
	@Override
	final public String toString()
	{
		return callGetCode();
	}

	/**
	 * This forces that each leaf of the abstract GOOL tree makes a getCode(this).
	 * So that the visitor generates code specifically for it.
	 * See wiki, Nitty Gritty details for more explanations.
	 * @return
	 */
	public abstract String callGetCode();
}
