package gool.ast.constructs;

public enum Operator {
	UNKNOWN, PLUS, MINUS, MULT, AND, OR, EQUAL, NOT, LT, LEQ, GT, GEQ, DECIMAL_PLUS, DECIMAL_MINUS, DIV, DECIMAL_DIV, DECIMAL_MULT, DECIMAL_LT, DECIMAL_LEQ, DECIMAL_GT, DECIMAL_GEQ, PREFIX_DECREMENT, POSTFIX_DECREMENT, PREFIX_INCREMENT, POSTFIX_INCREMENT, NOT_EQUAL;
}
