language: java

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y mono-devel mono-mcs
  - sudo apt-get install -y g++ libboost-all-dev
  - sudo apt-get install -y eclipse-cdt

script: 
  - ./gradlew test -i

branches:
  only:
  - master
