/* Generated By:JavaCC: Do not edit this line. ParserMethodInputTableTreeConstants.java Version 5.0 */
package gool.recognizer.common.parseMethod;

public interface ParserMethodInputTableTreeConstants
{
  public int JJTPARSETABLE = 0;
  public int JJTDECL_METHOD_MAPPING = 1;
  public int JJTGOOL_METHOD = 2;
  public int JJTLIST_PARAMS_GOOL = 3;
  public int JJTPARAM_GOOL = 4;
  public int JJTINPUT_METHOD = 5;
  public int JJTLIST_PARAMS_INPUT = 6;
  public int JJTPARAM_INPUT = 7;
  public int JJTDEFAULT_VALUE = 8;


  public String[] jjtNodeName = {
    "parseTable",
    "decl_method_mapping",
    "gool_method",
    "list_params_gool",
    "param_gool",
    "input_method",
    "list_params_input",
    "param_input",
    "default_value",
  };
}
/* JavaCC - OriginalChecksum=f45af52651b5e368c39418f813809f94 (do not edit this line) */
