/* Generated By:JavaCC: Do not edit this line. ParserMethodOutputTableTreeConstants.java Version 5.0 */
package gool.generator.common.parseMethod;

public interface ParserMethodOutputTableTreeConstants
{
  public int JJTPARSETABLE = 0;
  public int JJTDECL_METHOD_MAPPING = 1;
  public int JJTGOOL_METHOD = 2;
  public int JJTLIST_PARAMS_GOOL = 3;
  public int JJTPARAM_GOOL = 4;
  public int JJTOUTPUT_METHOD = 5;
  public int JJTLIST_PARAMS_OUTPUT = 6;
  public int JJTPARAM_OUTPUT = 7;
  public int JJTDEFAULT_VALUE = 8;


  public String[] jjtNodeName = {
    "parseTable",
    "decl_method_mapping",
    "gool_method",
    "list_params_gool",
    "param_gool",
    "output_method",
    "list_params_output",
    "param_output",
    "default_value",
  };
}
/* JavaCC - OriginalChecksum=de905d792e2a0a4e7ba7d6f76e8dd201 (do not edit this line) */
