/* Generated By:JavaCC: Do not edit this line. ParserClassInputTableTreeConstants.java Version 5.0 */
package gool.recognizer.common.parseClass;

public interface ParserClassInputTableTreeConstants
{
  public int JJTPARSETABLE = 0;
  public int JJTDECL_CLASS_MAPPING = 1;
  public int JJTGOOL_CLASS = 2;
  public int JJTINPUT_CLASS = 3;


  public String[] jjtNodeName = {
    "parseTable",
    "decl_class_mapping",
    "gool_class",
    "input_class",
  };
}
/* JavaCC - OriginalChecksum=b056c995341ba259446ae60a84a590c0 (do not edit this line) */
