/* Generated By:JavaCC: Do not edit this line. ParserClassOutputTableTreeConstants.java Version 5.0 */
package gool.generator.common.parseClass;

public interface ParserClassOutputTableTreeConstants
{
  public int JJTPARSETABLE = 0;
  public int JJTDECL_CLASS_MAPPING = 1;
  public int JJTGOOL_CLASS = 2;
  public int JJTOUTPUT_CLASS = 3;


  public String[] jjtNodeName = {
    "parseTable",
    "decl_class_mapping",
    "gool_class",
    "output_class",
  };
}
/* JavaCC - OriginalChecksum=a003e5bf36ef53bf471b1510267ce0ab (do not edit this line) */
