/* Generated By:JJTree&JavaCC: Do not edit this line. ParserClassOutputTableConstants.java */
package gool.generator.common.parseClass;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserClassOutputTableConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ID = 8;
  /** RegularExpression Id. */
  int STRING = 9;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_LINE_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"#\"",
    "\"\\n\"",
    "<token of kind 7>",
    "<ID>",
    "<STRING>",
    "\"<-\"",
  };

}
