package gool.ast;


/**
 * The type of the nodes which allow us to represent the Abstract Syntax Tree of
 * the intermediate language.
 */

public interface INode {
	/**
	 * The string representation of this node. It is used to generate the code
	 * for the target language.
	 * 
	 * @return the code generated by this node for the selected language.
	 */
	String toString();
}
